### ISSUE TITLE
ca sert a quoi caldera

### ISSUE THREAD

**Issue by BlueRed-Dev** [ramok0/PlataniumV3#13]
c quoi caldera pk tu peux pas launch sans

**Comment by BlueRed-Dev** [comment]
oh repond

**Comment by BlueRed-Dev** [comment]
pk tu close jveux juste savoir

**Comment by ramok0** [comment]
mais connard tu crée une issue pour rien pose la question sur discord rend pas fou

**Comment by BlueRed-Dev** [comment]
c quoi ton discord

**Comment by BlueRed-Dev** [comment]
ya pas de delai sur ps4
