### ISSUE TITLE
Latest patch support

### ISSUE THREAD

**Issue by Not-Bay** [ramok0/PlataniumV3#3]
Recent update breaks platanium
![imagen](https://github.com/Ramokprout/PlataniumV3/assets/60859158/c405065c-3cc3-4229-a8bf-f0056e4a2d8d)
There will be an update to fix this?

**Comment by ramok0** [comment]
Hey !

can you give me your settings that you used, debug websockets may be broken and bypass signatures is too

i'll update sigs for bypass signatures but since i never managed to do a proper websocket debug im not gonna update sigs for them

**Comment by ramok0** [comment]
just found a sig for validate_container_signature that works with UE 5.1 and UE 5.2
debug websockets sigs are still valid for UE 5.2 
i'll push it asap

**Comment by ramok0** [comment]
fixed in https://github.com/ramok0/PlataniumV3/commit/8acdb08f065e2533481f5c7172e39d0054e8d653
released in https://github.com/ramok0/PlataniumV3/releases/tag/v1.2.0

**Comment by xMistt** [comment]
I get this issue but running an old version of Fortnite (13.40).
