### ISSUE TITLE
Impossible to start Fortnite with Platanium V3 after the v25.20 update

### ISSUE THREAD

**Issue by tagadacandy** [ramok0/PlataniumV3#5]
Since the v25.20 update, the game will be stuck on "Collecting Dynamic Content" on start. 
This could be the error in the console that make the game loading infinitely 
![image](https://github.com/ramok0/PlataniumV3/assets/92104390/da0640b2-f316-4d36-bc63-63bcf54e7bc2)
![image](https://github.com/ramok0/PlataniumV3/assets/92104390/0962e0b0-dd4a-42a3-a60c-a5e14f5d555f)

**Comment by ramok0** [comment]
can you provide the config.json ?

**Comment by MazieK0nk** [comment]
I'm having the same issue and only have SSL disabled.

**Comment by tagadacandy** [comment]
> can you provide the config.json ?

{
    "debug_websockets": false,
    "detourURL": false,
    "device_auth": {
        "account_id": "5eb244b58d864cf7996bb43640bbe26c",
        "device_id": "9668681601354e868955c3ff36a6ac64",
        "secret": "AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAPuyozWlAxEu74re4v0yN7QAAAAACAAAAAAAQZgAAAAEAACAAAACFlrqplHv6m49ObOtxhbs/29F2f/DiYs+69Y8hT0GKRQAAAAAOgAAAAAIAACAAAABO3DjrK+dE0h6Xs1bqyizVblJWdzulBxRkAAR8I4+pcTAAAAAZ0AbsnxsnrXcgUUbO9QWv8SGzyH/ViieJjWRg7HWCc4EMpCK2adj6zvV0ksa9DiJAAAAAl6fey7unSOtVNj7ERHD9jxQUy0uPJvZx25qKyTlnZTdhtV+GChYPrwzW4qDs2WKwVGG0vqZX/XMawMtRblxkiQ=="
    },
    "disableSSL": false,
    "dump_aes": false,
    "fortnite_path": "C:\\Program Files\\Epic Games\\Fortnite",
    "forwardHost": "localhost",
    "forwardPort": 5000,
    "forwardProxy": "localhost:8000",
    "should_check_pak": true,
    "useProxy": false
}

This is my config file, but i already tried multiple options, and i'm not the only to have the issue

**Comment by tagadacandy** [comment]
After some search in the logs, i can say that the issue is coming from anything related to party creation.

**Comment by Ltsparten88** [comment]
Hey just an fyi you left your device auth in there I'd suggest deleting that people can log onto ur account with it if they see this

**Comment by Ltsparten88** [comment]
Specifically the "secret" part of it

**Comment by ramok0** [comment]
They cant use the device auth because the secret is ciphered with https://learn.microsoft.com/fr-fr/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

**Comment by tagadacandy** [comment]
> They cant use the device auth because the secret is ciphered with https://learn.microsoft.com/fr-fr/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

So have you found why the DLL is doing that ?

**Comment by ramok0** [comment]
it does that even without the dll, i think it makes this because there is no communication between the anticheat and fortnite
![image](https://github.com/ramok0/PlataniumV3/assets/63268168/6d5b1a7e-6ff8-40f3-9019-aab867aa1299)

**Comment by ramok0** [comment]
if this is true, the only possible way to solve this is to inject the dll while the anticheat is running like a cheat would do, but it would be very risky for fortnite accounts

**Comment by tagadacandy** [comment]
> if this is true, the only possible way to solve this is to inject the dll while the anticheat is running like a cheat would do, but it would be very risky for fortnite accounts

Yesterday, i tried multiple private servers who also inject a DLL, they were working fine.

**Comment by ramok0** [comment]
Can you send me a private server which supports latest ?

**Comment by tagadacandy** [comment]
> Can you send me a private server which supports latest ?

https://ezfn.dev/

It has Private Server and Hybrid

**Comment by ramok0** [comment]
ezfn works by redirecting traffic into a third party server, which works but it costs money, and i dont have money tbh

**Comment by ramok0** [comment]
im currently searching how can i fix the problem without hosting a server

**Comment by tagadacandy** [comment]
> im currently searching how can i fix the problem without hosting a server

I don't think XMPP traffic is sent to EZFN servers when using Hybrid. It should use official epic xmpp

**Comment by ramok0** [comment]
sure, it does not redirect XMPP, but it still redirects MCP and it still require a server

**Comment by tagadacandy** [comment]
> sure, it does not redirect XMPP, but it still redirects MCP and it still require a server

But when you start Fortnite with your launcher, without using anything related to proxy/detour url, why the mcp is still redirected, it should use epic servers like before

**Comment by ramok0** [comment]
My launcher does not redirect anything, thats why its not working, EZFN patches this by redirecting requests to their servers

**Comment by tagadacandy** [comment]
Just a question, what are the mcp with the issue, maybe i can try to fix that with my own backend ?

**Comment by ramok0** [comment]
to be exactly sure, we would have to decompile ezfn's dll and hook it to attach a proxy and see what are they overwritting

**Comment by tagadacandy** [comment]
> to be exactly sure, we would have to decompile ezfn's dll and hook it to attach a proxy and see what are they overwritting

Step one: finding ezfn dll

i swear ezfn have a very weird system to store his files

**Comment by ramok0** [comment]
i already have it

**Comment by ramok0** [comment]
%localappdata%\EZFNCore\Addons and it looks like they download the dll at each start of the game

**Comment by ramok0** [comment]
0x8880 ; __int64 __fastcall curl_easy_setopt_hook(__int64 curlhandle, __int64 opt, void **data, __int64 (__fastcall *call_original)(__int64, __int64, void **))

**Comment by tagadacandy** [comment]
> 0x8880 ; __int64 __fastcall curl_easy_setopt_hook(__int64 curlhandle, __int64 opt, void **data, __int64 (__fastcall *call_original)(__int64, __int64, void **))

What is doing this code line ?

**Comment by ramok0** [comment]
its the function definition that i have to hook to be able to get ezfn traffic

**Comment by tagadacandy** [comment]
Any news ?

**Comment by Ltsparten88** [comment]
> it does that even without the dll, i think it makes this because there is no communication between the anticheat and fortnite ![image](https://user-images.githubusercontent.com/63268168/256493615-6d5b1a7e-6ff8-40f3-9019-aab867aa1299.png)

Try suspending the anticheat instead of killing it, I do that on my own launcher and it seems to work fine with my stuff but idk 100% if that's the issue

**Comment by Ltsparten88** [comment]
I don't think it's a communication error with AC but assuming it is try that

**Comment by nathanlev76** [comment]
> > it does that even without the dll, i think it makes this because there is no communication between the anticheat and fortnite ![image](https://user-images.githubusercontent.com/63268168/256493615-6d5b1a7e-6ff8-40f3-9019-aab867aa1299.png)
> 
> Try suspending the anticheat instead of killing it, I do that on my own launcher and it seems to work fine with my stuff but idk 100% if that's the issue

How can i do that ? Anything to change when starting the game ?

**Comment by nathanlev76** [comment]
> > > it does that even without the dll, i think it makes this because there is no communication between the anticheat and fortnite ![image](https://user-images.githubusercontent.com/63268168/256493615-6d5b1a7e-6ff8-40f3-9019-aab867aa1299.png)
> > 
> > 
> > Try suspending the anticheat instead of killing it, I do that on my own launcher and it seems to work fine with my stuff but idk 100% if that's the issue
> 
> How can i do that ? Anything to change when starting the game ? I don't want to risk any ban because of a dumb fail

Just did a test to start a regular fortnite without any anticheat using args (from a bat file) and it was working fine

**Comment by nathanlev76** [comment]
Can we talk on Discord or anything else, it will be easier than GitHub, my discord name is @tagadacandy

**Comment by tagadacandy** [comment]
I HAVE FOUND THE ISSUE AND HOW TO FIX ! 
You actually need to add two more args to the command line to start fortnite
They are -fromfl and -caldera
You can know the value to add to them using the Epic caldera endpoint to get the current anti cheat of the current logged account.

**Comment by ramok0** [comment]
i'll implement caldera and push if its working as expected

**Comment by ramok0** [comment]
I might have repaired it unintentionally lmfao

**Comment by ramok0** [comment]
fixed for me in https://github.com/ramok0/PlataniumV3/commit/f48d5626a4803a12a34fea97374518a9fb5bde12
pre release so you can test and tell me if its working : https://github.com/ramok0/PlataniumV3/releases/tag/v1.3.0-pre

**Comment by tagadacandy** [comment]
> fixed for me in [f48d562](https://github.com/ramok0/PlataniumV3/commit/f48d5626a4803a12a34fea97374518a9fb5bde12) pre release so you can test and tell me if its working : https://github.com/ramok0/PlataniumV3/releases/tag/v1.3.0-pre

I have just tried it, it's working FINE ! 
But my current anti cheat is BattleEye, i didn't try with EAC yet

**Comment by ramok0** [comment]
Same, i couldnt get EAC

**Comment by ramok0** [comment]
i added support for eos in https://github.com/ramok0/PlataniumV3/commit/f6c4717aaa38d1d4b600d97ae55b4637bca56cc3

**Comment by Aiyzox** [comment]
Im Eos today, I will test

**Comment by Aiyzox** [comment]
that's working

**Comment by ramok0** [comment]
pre release for testings : https://github.com/ramok0/PlataniumV3/releases/tag/v1.3.0-pre.2

**Comment by ramok0** [comment]
issue solved
