### ISSUE TITLE
Add a way to enter in the fortnite save the world games

### ISSUE THREAD

**Issue by Aiyzox** [ramok0/PlataniumV3#8]

**Comment by ramok0** [comment]
It will be avaliable in https://github.com/ramok0/PlataniumV3/issues/7

**Comment by Aiyzox** [comment]
ok, thx.
Youre french ?

**Comment by ramok0** [comment]
oi

**Comment by Aiyzox** [comment]
T'aurai un discord ?

**Comment by ramok0** [comment]
J'utilise seulement le protocole matrix & mail

**Comment by Aiyzox** [comment]
Comment fonctionne Matrix ?

**Comment by ramok0** [comment]
C'est un protocole de communication instantané décentralisé et open source, t'as juste à télécharger un client (le plus complet je trouve que c'est https://matrix.org/ecosystem/clients/element/), et ensuite ça fonctionne comme Discord mais plus sécurisé

**Comment by Aiyzox** [comment]
J'ai installé matrix, comment on ajoute des personnes ?

**Comment by ramok0** [comment]
![image](https://github.com/ramok0/PlataniumV3/assets/63268168/2fdf9302-fc35-4936-9a36-58ec17d622fd)

il suffit juste de démarrer une nouvelle conversation et de mettre l'id du mec que tu veux parler avec

**Comment by Aiyzox** [comment]
ok, c'est quoi ton id a toi ?

**Comment by ramok0** [comment]
@guise1783:matrix.org de mémoire je crois
